
# Gem::Specification for Github_hook-0.5.0
# Originally generated by Echoe

Gem::Specification.new do |s|
  s.name = %q{github_hook}
  s.version = "0.5.0"

  s.specification_version = 2 if s.respond_to? :specification_version=

  s.required_rubygems_version = Gem::Requirement.new(">= 0") if s.respond_to? :required_rubygems_version=
  s.authors = ["Rob Sanheim"]
  s.date = %q{2008-05-09}
  s.description = %q{Wrapper around the github post receive JSON payload.}
  s.email = %q{opensource@thinkrelevance.com}
  s.extra_rdoc_files = ["History.txt", "lib/github_hook.rb", "README.txt"]
  s.files = ["History.txt", "lib/github_hook.rb", "Manifest", "README.txt", "spec/github_hook_spec.rb", "spec/helper.rb", "spec/payload.rb", "spec/vendor/bacon-0.9.0/bin/bacon", "spec/vendor/bacon-0.9.0/COPYING", "spec/vendor/bacon-0.9.0/lib/bacon.rb", "spec/vendor/bacon-0.9.0/Rakefile", "spec/vendor/bacon-0.9.0/RDOX", "spec/vendor/bacon-0.9.0/README", "spec/vendor/bacon-0.9.0/test/spec_bacon.rb", "github_hook.gemspec"]
  s.has_rdoc = true
  s.homepage = %q{http://opensource.thinkrelevance.com/wiki/github_hook}
  s.rdoc_options = ["--line-numbers", "--inline-source", "--title", "Github_hook", "--main", "README.txt"]
  s.require_paths = ["lib"]
  s.rubyforge_project = %q{thinkrelevance}
  s.rubygems_version = %q{1.1.1}
  s.summary = %q{Wrapper around the github post receive JSON payload.}
  s.test_files = ["spec/github_hook_spec.rb"]
end


# # Original Rakefile source (requires the Echoe gem):
# 
# require 'rubygems'
# require 'echoe'
# require './lib/github_hook.rb'
# 
# Echoe.new('github_hook', GithubHook::VERSION) do |p|
#   p.rubyforge_name = 'thinkrelevance'
#   p.author = 'Rob Sanheim'
#   p.email = 'opensource@thinkrelevance.com'
#   p.summary = "Wrapper around the github post receive JSON payload."
#   p.url = "http://opensource.thinkrelevance.com/wiki/github_hook"
#   p.rdoc_pattern = /^(lib|bin|ext)|txt|rdoc|CHANGELOG|MIT-LICENSE$/
#   rdoc_template = `allison --path`.strip << ".rb"
#   p.rdoc_template = rdoc_template
#   p.test_pattern = 'spec/**/*_spec.rb'
# end